# Generated by Django 3.0 on 2019-12-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branch_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='holder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Customer'),
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(default='Earth', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='Email', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_options',
            field=models.CharField(choices=[('savings', 'SAVINGS'), ('checking', 'CHECKING')], default=('savings', 'SAVINGS'), max_length=30),
        ),
    ]
