# Generated by Django 3.0 on 2019-12-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_options',
        ),
    ]
