# Generated by Django 3.0.1 on 2019-12-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_customer_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
    ]
